version: "3.9"

services:
  postgress:
    image: postgres:15
    container_name: telemetry_postgress
    environment:
      - POSTGRES_USER: dev
      - POSTGRES_PASSWORD: dev
      - POSTGRES_DB: telemetry
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  telemetry-api:
    build: .
    container_name: telemetry_api
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - postgress
    volumes:
      - .:/app